# This is a basic workflow to help you get started with Actions

name: CI

# Every new pull request to develop branch must fire CI check
on: [pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: Run Unit Testing
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Install all dependencies
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: install

      - name: Run unit testing
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: projects:cli:test

      - name: Run eslint
        uses: borales/actions-yarn@v2.3.0
        with:
          cmd: projects:lint